name: rolling_tab_bar
description: A Flutter tab bar with a rolling active indicator behind each icon
version: 0.0.1-alpha
author: Craig Labenz <craig.labenz@gmail.com>
homepage: https://github.com/craiglabenz/flutter_rolling_tab_bar

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  polygon_clipper: ^1.0.2
  tinycolor: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
